// SPDX-License-Identifier: MIT
// Copyright © 2022 The Tvix Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tvix/build/protos/rpc_build.proto

package buildv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tvix_build_protos_rpc_build_proto protoreflect.FileDescriptor

const file_tvix_build_protos_rpc_build_proto_rawDesc = "" +
	"\n" +
	"!tvix/build/protos/rpc_build.proto\x12\rtvix.build.v1\x1a\x1dtvix/build/protos/build.proto2L\n" +
	"\fBuildService\x12<\n" +
	"\aDoBuild\x12\x1b.tvix.build.v1.BuildRequest\x1a\x14.tvix.build.v1.BuildB$Z\"code.tvl.fyi/tvix/build-go;buildv1b\x06proto3"

var file_tvix_build_protos_rpc_build_proto_goTypes = []any{
	(*BuildRequest)(nil), // 0: tvix.build.v1.BuildRequest
	(*Build)(nil),        // 1: tvix.build.v1.Build
}
var file_tvix_build_protos_rpc_build_proto_depIdxs = []int32{
	0, // 0: tvix.build.v1.BuildService.DoBuild:input_type -> tvix.build.v1.BuildRequest
	1, // 1: tvix.build.v1.BuildService.DoBuild:output_type -> tvix.build.v1.Build
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tvix_build_protos_rpc_build_proto_init() }
func file_tvix_build_protos_rpc_build_proto_init() {
	if File_tvix_build_protos_rpc_build_proto != nil {
		return
	}
	file_tvix_build_protos_build_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tvix_build_protos_rpc_build_proto_rawDesc), len(file_tvix_build_protos_rpc_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tvix_build_protos_rpc_build_proto_goTypes,
		DependencyIndexes: file_tvix_build_protos_rpc_build_proto_depIdxs,
	}.Build()
	File_tvix_build_protos_rpc_build_proto = out.File
	file_tvix_build_protos_rpc_build_proto_goTypes = nil
	file_tvix_build_protos_rpc_build_proto_depIdxs = nil
}
